---
- name: This configures modules on a Webserver to handle updates.
  hosts: myblog
#  hosts: webservers
#  hosts: 18.222.165.39
#  hosts: 18.222.208.55
  become: true
  tasks:
    - name: Become Root
      shell:
        cmd: sudo su

    - name: Install, Update, and Configure Services for a Webserver
      block:
        - name: HTTPD/Apache [1/5]
          block:
    
            - name: HTTPD/Apache [1/2] (install)
              package: 
                name: httpd
                state: present
            
            - name: HTTPD/Apache [2/2] (enable)
              service:
                name: httpd
                state: started
                enabled: yes
    

        - name: FirewallD [2/5]
          block:

            - name: FirewallD [1/3] (install)
              package:
                name: firewalld
                state: present
            
            - name: FirewallD [2/3] (enable)
              service:
                name: firewalld
                state: started
                enabled: yes

            - name: FirewallD [3/3] (Configure)
              block:
                - name: Opens port 80 for http access.
                  firewalld:
                    service: http
                    permanent: true
                    immediate: true
                    state: enabled
                - name: Opens port 443 for https access.
                  firewalld: 
                    service: https
                    permanent: true
                    immediate: true
                    state: enabled
#                - name: Opens for 8000 for splunk.
#                  firewalld: 
#                    service: splunk
#                    permanent: true
#                    immediate: true
#                    state: enabled
#        - name: splunk
#          block:
#          - name: Copies Splunk(MAIN)RPM to host
#            copy:
#              src: ../../../../software-installers/splunk-8.1.3-63079c59e632-linux-2.6-x86_64.rpm
#              dest: ~
#              mode: 644
#          - name: Installs Splunk RPM
#            shell:
#              cmd: rpm -i ~/splunk-8.1.3-63079c59e632-linux-2.6-x86_64.rpm

        - name: mod_ssl [3/5]
          block:

            - name: mod_ssl [1/1] (install)
              package:
                name: mod_ssl
                state: present

        - name: snapd [4/5]
          block:
            
            - name: Upgrades and adds EPEL packages
              shell:
                cmd: yes 'y' | dnf install epel-release -y
            
            - name: Upgrading EPEL packages
              shell:
                cmd: yes 'y' | dnf upgrade -y

            - name: Install snapd
              yum:
                name: snapd
                state: present

            - name: Enable systemctl for snapd
              shell:
                cmd: systemctl enable --now snapd.socket
#-----------------------------------------------------
#This section is already handled on the server of interest. If
#needed, do this BY HAND on new servers, or test this!
#            - name: Symbolic-ly link snapd local to snapd bin
#              shell:
#                cmd: ln -s /var/lib/snapd/snap /snap
#-----------------------------------------------------
        - name: certbot [5/5]
          block:
            
            - name: Install Certbot
              shell:
                cmd: snap install --classic certbot

            - name: Copies Apache Config Files for SSLCert
              copy:
                src: apacheconfig/
                dest: /etc/httpd/conf.d/
                mode: '0644'

#------------------------------------------------------
#Sym-links seem upset. Maybe because they already exist and it causes
#strange errors? Regardless, ignore this and test on future hosts.
#
#            - name: Symbolic-ly Link Certbot
#              shell:
#                cmd: ln -s /snap/bin/certbot centos/bin/certbot
#------------------------------------------------------
      tags:
        - setup
        - all
      

    - name: Updates packages and shows changes
      block:
    
        - name: Updates all packages
          package:
            state: latest
            name: '*'
          when: ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf" or ansible_pkg_mgr == "apt"
          tags: 
            - update
            - all
          register: system_update

        - name: Show package changes
          debug: 
            var: system_update
          when: system_update.changed
          tags:
            - update
            - all
      tags:
        - update
        - all
        - restart

    - name: Restarts all services
      block:
        
        - name: Restart HTTPD
          service:
            name: httpd
            state: restarted
        - name: Restart firewalld
          service:
            name: firewalld
            state: restarted
      tags: 
        - restart
        - update
        - all
